name: Generate and deploy

on:  
  push:
    branches: [ main ]
    
  workflow_dispatch:
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        
      - name: Install and build
        run: |
          npm install imml commander html-minifier jsdom
          npx imml index.imml
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: deploy
          folder: dist/index
